"""empty message

Revision ID: 1732fe46c183
Revises: None
Create Date: 2015-05-21 00:14:18.704000

"""

# revision identifiers, used by Alembic.
revision = '1732fe46c183'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('userdata', sa.Column('password', sa.String(length=250), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('userdata', 'password')
    ### end Alembic commands ###
